{
 "title": "Core Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Network received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes:rate:sum{instance=\"3.15.238.227:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"3.15.238.227:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"3.15.238.227:9100\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"3.15.238.227:9100\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "instance:node_cpu:rate:sum{instance=\"3.15.238.227:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}